{{- if .Values.security.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.name" . }}-auth
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
type: Opaque
data:
  htpasswd: {{ htpasswd .Values.security.authentication.credentials.username .Values.security.authentication.credentials.password | b64enc }}
{{- end }}
---
{{- if .Values.security.certificates.autoGenerate }}
{{- $cert := genSelfSignedCert .Values.security.certificates.domain nil (list .Values.security.certificates.domain) 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" . }}-tls
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificates
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}