apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-registry.name" . }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.service.type }}
  ports:
    - port: {{ .Values.networking.service.port }}
      targetPort: {{ .Values.networking.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "docker-registry.selectorLabels" . | nindent 4 }}
